const COVER_LETTER_REVIEW_VERSION = 1;
const REVIEW_WEIGHTS = { factualAccuracy: .25, profileAlignment: .20, jobAlignment: .20, evidenceUsage: .15, hallucinationRisk: .10, style: .05, personalization: .05 };
const REVIEW_THRESHOLDS = { veryGood: 90, good: 75, recommended: 60 };
function createEmptyCoverLetterReview() { const area = () => ({ score: 0, status: "", issues: [] }); return { version: 1, overallScore: 0, verdict: "", factualAccuracy: area(), profileAlignment: area(), jobAlignment: area(), evidenceUsage: area(), hallucinationRisk: area(), style: area(), personalization: area(), length: area(), issues: [], strengths: [], recommendations: [], reviewedAt: "", coverLetterGeneratedAt: "" }; }
function reviewVerdict(score) { return score >= REVIEW_THRESHOLDS.veryGood ? "Sehr gute Qualität" : score >= REVIEW_THRESHOLDS.good ? "Gute Qualität" : score >= REVIEW_THRESHOLDS.recommended ? "Überarbeitung empfohlen" : "Deutliche Überarbeitung erforderlich"; }
function calculateReviewScore(review) { const weighted = Object.entries(REVIEW_WEIGHTS).reduce((sum, [key, weight]) => sum + Math.max(0, Math.min(100, Number(review[key]?.score) || 0)) * weight, 0); const issues = review.issues || []; const criticalTypes = ["factual", "factualAccuracy", "hallucination", "hallucinationRisk"]; const critical = issues.some(issue => issue.severity === "critical" && criticalTypes.includes(issue.type)); const hasHigh = issues.some(issue => issue.severity === "high"); const hasMedium = issues.some(issue => issue.severity === "medium"); const minimum = critical ? 0 : hasHigh ? 60 : hasMedium ? 60 : issues.some(issue => issue.severity === "low") ? 75 : 0; return Math.min(critical ? 59 : 100, Math.max(minimum, Math.round(weighted))); }
function finalizeCoverLetterReview(review) { const result = { ...createEmptyCoverLetterReview(), ...review }; result.overallScore = calculateReviewScore(result); result.verdict = reviewVerdict(result.overallScore); result.reviewedAt = result.reviewedAt || new Date().toISOString(); return result; }
function validateCoverLetterReview(review) { const errors = []; if (!review || review.version !== 1) errors.push("Ungültige Review-Version."); ["factualAccuracy", "profileAlignment", "jobAlignment", "evidenceUsage", "hallucinationRisk", "style", "personalization", "length"].forEach(key => { if (!review?.[key] || !Number.isFinite(Number(review[key].score)) || Number(review[key].score) < 0 || Number(review[key].score) > 100 || !Array.isArray(review[key].issues)) errors.push(`${key} ist ungültig.`); }); if (review && (!Array.isArray(review.issues) || !Array.isArray(review.strengths) || !Array.isArray(review.recommendations))) errors.push("Review-Listen fehlen."); return errors; }
function assertValidCoverLetterReview(review) { const errors = validateCoverLetterReview(review); if (errors.length) throw new Error(errors.join(" ")); return review; }
function buildReviewProfile(profile) { return { summary: profile.summary || "", experience: profile.experience || [], education: profile.education || [], skills: profile.skills || {}, projects: (profile.projects || []).map(project => ({ id: project.id, name: project.name, description: project.description || "", technologies: project.technologies || [], role: project.role || "", activities: project.activities || [] })), additional: { languages: profile.additional?.languages || [] } }; }
